### ISSUE TITLE
--interfaces option doesn't accept a comma separated string of interface names

### ISSUE THREAD

**Issue by jollyrogue** [branchnetconsulting/so1404-ntopng-installer#1]
If there are multiple interfaces on an SO box, the script will produce a ntopng.conf file with a line "--interface=eth1,eth2 eth3", and this results in ntopng looking for an interface named "eth1,eth2 eth3". To specify multiple interfaces, the "--interface" option needs to be specified for each interface to monitor. The man page isn't clear about this this, and I had to find a mailing list thread to figure this out.

Current output:
--interface=eth1,eth2 eth3

Needed output:
--interface=eth1
--interface=eth2
--interface=eth3

Line 100 is the line that needs to be wrapped in a loop which iterates through the $IFACE variable.

Something like:
for i in $IFACE
do
    echo "--interface=$i" >> /etc/ntopng/ntopng.conf.dist
done

That's just off the top of my head, so I'm not sure that's going to work.

**Comment by branchnetconsulting** [comment]
Hi jollyrogue,

Actually, both using a comma separated interface list and specifying one interface per line in the ntopng.conf file are valid, though they have different results.   When ntopng encounters a comma separated interface list, it essentially bonds the traffic from all of those interfaces together and then reports on them as if their traffic were all showing up on a single interface.  Specifying interfaces on separate lines tells ntopng to report separately on each interface's traffic flows.  In that case the reporting is more specific but also requires you to jump back and forth between interfaces in the ntopng web console in order to see the big picture.  

My intention in my script was to generate a single interface line with a single interface or a comma separated list of interfaces in it.  I see I had a typo in it that caused missing commas.  I just now fixed it 
( https://github.com/branchnetconsulting/so1404-ntopng-installer/commit/ec6e2843db43eb55b8157048952ff5792d6474a6 )

Now the script should produce
--interface=eth1,eth2**,**eth3
instead of
--interface=eth1,eth2 eth3

Thanks for bringing this to my attention.
Kevin
