### ISSUE TITLE
pfring 6.4

### ISSUE THREAD

**Issue by sbaker-gre** [branchnetconsulting/so1404-ntopng-installer#2]
I receive this message running on an up to date Security Onion sensor.

The currently running securityonion-pfring version is 6.2.0 but the one in the stable ntop repo for ntopng is 6.4.0.  These must be the same.  You might try running "sudo soup" to see if a newer securityonion-pfring version is available.

**Comment by branchnetconsulting** [comment]
Hi, it appears that the ntop folks have upgraded the latest stable version
of ntop-ng to use pfring 6.4.0 instead of 6.2.0.  The latest Security Onion
presently requires pfring 6.2.0.  Let me follow up with the ntop team to
see how we can resolve this.

Kevin

**Comment by branchnetconsulting** [comment]
I am awaiting a response from the ntop folks.  Hopefully they will provide us with the latest ntopng  package versions that are still compatible Security Onion.  Otherwise I'll have to fall back to the latest I have on hand.

http://www.gossamer-threads.com/lists/ntop/users/41569

**Comment by branchnetconsulting** [comment]
Hi,

As hopefully only a temporary measure, I have adapted the script to use back versions of the needed ntopng and pfring deb files instead of the latest stable ones from ntop.org.  These are the versions I last successfully used with my installer script.  Once SO moves to PF_RING 6.4, I should be able to get things tracking with the latest stable ntopng again.  

Please give the installer a try now.

Kevin

**Comment by sbaker-gre** [comment]
I see that you uploaded the .deb files but it doesn't look like the installer script has been updated to use them. Running the current script I still get the same message. Did you miss the script during the commit or did you intend some other way to install?

**Comment by branchnetconsulting** [comment]
You are correct.  I'm so sorry about that.  It is committed now.

Kevin

**Comment by sbaker-gre** [comment]
It is working now. Thank you very much for your time and effort Kevin.

Steve
