### ISSUE TITLE
Current Status?

### ISSUE THREAD

**Issue by tnynyn** [branchnetconsulting/so1404-ntopng-installer#3]
Hi,

I just tried using this to install NTOPNG on my SO box, but it seems to install NTOPNG 3.4 instead of 3.0, is there anyway to make it install 3.0?  While 3.4 did work, SO did not (I think it was due to PF_RING being upgraded to 7.0 due the 3.4 requirement)

**Comment by branchnetconsulting** [comment]
Hi,

Are you running Security Onion on Ubuntu 14.04 or 16.04?  The 16.04 version
has not come out of testing yet, and my SO-specific ntopnp installer
assumes a 14.04 platform at this time.

Did you follow the procedure here:

https://github.com/branchnetconsulting/so1404-ntopng-
installer/blob/master/README.md

that uses my script to perform the install of NTOPNG, or did you do a
standard apt-get install?  I ask because a standard apt-get install of
ntopng on Security Onion will indeed break Security Onion processes that
depend on PF_RING because the ntopng deb will pull in a conflicting version
of PF_RING.  If you did do the apt-get install of ntopng, then first you
need to remove it and reinstall the SO pfring package to fix SO.

apt-get remove pfring ntopng
apt-get install --reinstall securityonion-pfring-module

then try using the procedure in the link I shared above.  If that breaks on
a recently updated Ubuntu 14.04 SO system, please let me know.

Kevin

**Comment by branchnetconsulting** [comment]
I just ran my ntopng installer script on an Ubuntu 14.04 SO system, and it
installed ntopng-3.4 while not replacing SO's pfring 6.6 package with
pfring 7.  I did find that ntopng-3.4 introduced a new package dependency
(libnetfilter-conntrack3) which I just now added to my installer script.
Ntopng-3.4 is showing traffic, and other SO packet capture tools are
getting traffic, too.  Looks good to me.

Kevin

On Wed, May 9, 2018 at 11:12 PM, Kevin Branch <kevin@branchnetconsulting.com
> wrote:

> Hi,
>
> Are you running Security Onion on Ubuntu 14.04 or 16.04?  The 16.04
> version has not come out of testing yet, and my SO-specific ntopnp
> installer assumes a 14.04 platform at this time.
>
> Did you follow the procedure here:
>
> https://github.com/branchnetconsulting/so1404-ntopng-install
> er/blob/master/README.md
>
> that uses my script to perform the install of NTOPNG, or did you do a
> standard apt-get install?  I ask because a standard apt-get install of
> ntopng on Security Onion will indeed break Security Onion processes that
> depend on PF_RING because the ntopng deb will pull in a conflicting version
> of PF_RING.  If you did do the apt-get install of ntopng, then first you
> need to remove it and reinstall the SO pfring package to fix SO.
>
> apt-get remove pfring ntopng
> apt-get install --reinstall securityonion-pfring-module
>
> then try using the procedure in the link I shared above.  If that breaks
> on a recently updated Ubuntu 14.04 SO system, please let me know.
>
> Kevin
>

**Comment by tnynyn** [comment]
I am running 14.04, I think I borked something up along the way, going to reinstall again later today and will give you an update.  Thanks for the help!

**Comment by tnynyn** [comment]
Reporting back after reinstall, all is good! Thanks again!
